### ISSUE TITLE
Error building iOS plugin for Godot 

### ISSUE THREAD

**Issue by BraveEvidence** [kyoz/godot-flashlight#2]
### Godot version

4.2.2

### Plugin version

v1.0.0

### Phone information

iPhone 10

### Issue description

Hi, this is not an issue with your library. I am trying to learn how to create an iOS plugin from scratch.  I downloaded the Godot source code from Github and ran `scons platform=ios target=template_debug -j4` to generate ios headers. Then i created a static library using Xcode and copied
`flashlight_module.mm`, `flashlight.h`, `flashlight.gdip`, `flashlight.mm`, `flashlight_module.h` 

I also went to Header Search Path in Build Settings and added this path /Users/Desktop/godot/platform/ios. Now when i try to build the project i get error saying` 'core/engine.h' file not found`

Now i tried creating an xcframework as well using Xcode and copied all the files and set the Header Search Path and with that approach i get ton of errors.

What am i missing?

### Steps to reproduce

Above Steps

**Comment by kyoz** [comment]
For ios you need to build `extracted headers` correctly. Or else everything will break. You can see my [ios-extracted-headers repo](https://github.com/kyoz/godot-ios-extracted-headers) for more detail on building it correctly. You can also use my build in [release page](https://github.com/kyoz/godot-ios-extracted-headers/releases/tag/stable) to build your plugin, no need to build the headers over and over.

One more important thing is that in your plugins, name must be correct, `flashlight` and `Flashlight` are different. Make sure the plugin build and run well before you add more code to it to limit the errors.

**Comment by BraveEvidence** [comment]
@kyoz Thank you for your reply. I tried downloading the repo and added 4.2.2 to build.env as the release page does not have 4.2.2 version of Godot but I get error saying

```
>> Install Godot source...
- Your template version is not supported yet :'(
>> Extract Godot source...
tar: Error opening archive: Failed to open '.cache/godot-4.2.2-stable.tar.xz'
mv: rename godot-4.2.2-stable to godot: No such file or directory
>> Generate Godot headers...
./scripts/generate-headers.sh: line 3: cd: ./godot: No such file or directory
./scripts/generate-headers.sh: line 9: ./../scripts/timeout: No such file or directory
>> Extract Godot headers...
rsync: link_stat "/Users/transformhub/Downloads/godot-ios-extracted-headers-main/./godot" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/ce725a5f-c761-11ee-a4ec-b6ef2fd8d87b/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
>> Pack Godot extracted headers...
./scripts/extract-headers.sh: line 38: cd: bin/extracted_headers: No such file or directory

zip error: Nothing to do! (try: zip -r -q extracted_headers_godot_4.2.2.zip . -i godot/)
mv: rename bin/extracted_headers/extracted_headers_godot_4.2.2.zip to .release/extracted_headers_godot_4.2.2.zip: No such file or directory
```


Also I tried downloading Godot v4.2.1 headers from you release page and I still get the same issue. I updated the Header search path as well `/Users/Downloads/godot/platform/iOS` in Xcode. Rest of the code I have just copied it from your flashlight repo so I don't think there could be any mistake as such regarding case sensitivity

**Comment by kyoz** [comment]
[extracted_headers_godot_4.2.2.zip](https://github.com/kyoz/godot-flashlight/files/15186496/extracted_headers_godot_4.2.2.zip)

I've build it for you, it's seem you for got the quotes `"`. Try this header with your plugins. If it not work, it will likely due to something else in your plugin codes.

**Comment by BraveEvidence** [comment]
@kyoz Thank you for the reply.

I am stilling facing the same issue. If you have some free time please have a look at my [code](https://github.com/BraveEvidence/SampleGodotIosPlugin). I just copy pasted everything from your flashlight repo in my Xcode static library. 


Also just wanted to check while setting Header path I am entering `/Users/Downloads/godot/platform/ios` , is this correct?

**Comment by kyoz** [comment]
You missing a `SConstruct` file. Building an plugin is not hard but we have to follow the workflow that core team has show. You can take a look at [this repo](https://github.com/naithar/godot_ios_plugin). My plugins are build to run on Github action so i've tweak em a lots and they are pretty complicated.
 
 Take a look at that repo and try to build it, when it built. You can use it as an `iOS plugin template`

**Comment by BraveEvidence** [comment]
Thank you. When I run `scons platform=ios arch=arm64 target=release_debug target_name=flashlight version=4.0 target_path=/Users/Desktop/mytrial/flashlightol` to generate a static library I get error saying `No valid plugin selected`. I updated the code [here](https://github.com/BraveEvidence/SampleGodotIosPlugin/tree/main/plugin)

**Comment by BraveEvidence** [comment]
Ok I resolved that issue using `scons platform=ios arch=arm64 target=release_debug target_name=flashlight version=4.0 target_path=/Users/transformhub/Desktop/mytrial plugin=flashlight`

but getting a new one

```
ar rc /Users/transformhub/Desktop/libmytrialflashlight.arm64-ios.release_debug.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
scons: *** [/Users/transformhub/Desktop/libmytrialflashlight.arm64-ios.release_debug.a] Error 1
scons: building terminated because of errors.

```

**Comment by kyoz** [comment]
I don't know what `target_path` you are using is?

But the simple build command should be like this:

```
scons target=release_debug arch=arm64 plugin=flashlight version=4.0
```

**Comment by kyoz** [comment]
Also, you must follow the repo that you copied the `SConstruct` file. There is this config (Which is where your plugin files be) 
https://github.com/naithar/godot_ios_plugin/blob/master/SConstruct#L171

**Comment by BraveEvidence** [comment]
If I just run `scons target=release_debug arch=arm64 plugin=flashlight version=4.0` I get error saying `scons: *** Path for option target_path does not exist: bin/`, also I updated my `SConstruct` file, can you check [here](https://github.com/BraveEvidence/SampleGodotIosPlugin/tree/main/plugin)

**Comment by kyoz** [comment]
[SampleGodotIosPlugin-main 2.zip](https://github.com/kyoz/godot-flashlight/files/15188044/SampleGodotIosPlugin-main.2.zip)
![Screenshot 2024-05-02 at 19 11 54](https://github.com/kyoz/godot-flashlight/assets/29815830/2c42b612-72d3-4661-8b74-1a4c957867fb)

This is working source which i edited from yours.

Notes:

- `godot` folder: extract headers here
- `bin`: create an empty folder, your build files will be here
-  Important: your file structure is wrong, it must follow like mine, or else you have to edit in `SConstruct` file
Hope it help

**Comment by BraveEvidence** [comment]
Absolutely Brilliant. Thanks man. Sorry to waste so much of your time

**Comment by BraveEvidence** [comment]
@kyoz  Do you have any idea on how to integrate an Native Android View / SwiftUI View like SwiftUI Charts in a Godot Screen. Like embed any Native mobile view in any Godot screen. I know it was possible using [GAST plugin](https://github.com/m4gr3d/GAST) for Godot 3, anything on Godot 4 you're aware about? I know this might seem a bit odd of integrating native mobile view in Godot but if a complex functionality is already available in Native Mobile code why not reuse it in Godot, instead of creating it from scratch.

**Comment by kyoz** [comment]
As i know it's pretty hard. I think you have to create your own node to represent the embedded view, and make sure for it to work stable is not easy. I think you should digging more in that plugin to see how him do that and writing your own one. I think you can search for some keyword like "Embedded View", "Native Control" in Godot. There maybe someone doing this before and have some expericence.

**Comment by BraveEvidence** [comment]
@kyoz  Do you have experience of integrating swift with objective-c++.  I have created a simple static library, check [here](https://github.com/BraveEvidence/GodotSwiftTry) for code. I have experience of integrating swift in objective-c++, I have done it for react-native. [Here](https://youtu.be/OMJLjLwyxIo?t=342) is a sample video on that. but as soon as I run `scons target=release_debug arch=arm64 plugin=arithematic version=4.0` I get error saying 


```
arithematic/arithematic.mm:10:9:{10:9-10:30}: fatal error: 'arithematic-Swift.h' file not found [1]
 #import "arithematic-Swift.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [arithematic/arithematic.o] Error 1
scons: building terminated because of errors.
```

Everything looks fine in Build Settings
<img width="621" alt="Screenshot 2024-05-04 at 2 48 17 PM" src="https://github.com/kyoz/godot-flashlight/assets/24708929/864b3eb9-87c7-45e7-8373-d96fd08f9d30">
